run-gRPC-server:
	go run src/api/main.go gRPC-server
run-mom-server:
	go run src/api/main.go mom-server
run-api-gw:
	go run src/api/main.go api-gw
run-rabbitmq:
	docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.12-management